### ISSUE TITLE
Failes on missed font

### ISSUE THREAD

**Issue by sgf-dma** [unclechu/place-cursor-at#1]
Hi.

I've seen the following error

    $ place-cursor-at
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: user error (loadQueryFont)
    place-cursor-at: thread blocked indefinitely in an MVar operation

until i've installed `xfonts-terminus` and restarted X server on Debian 8
system. May be fallback to another font or use `fontconfig` somehow?

(можно писать по-русски? Честно говоря, я так и не понял, что программа делает; перемещает курсор в одном окне? Или между разными? Но это я так, к слову; может, опишите это более подробно в README.)

**Comment by unclechu** [comment]
@sgf-dma Now it’s falling back to default font if Terminus couldn’t be loaded.

**Comment by unclechu** [comment]
@sgf-dma Also another paragraph has been added to the top of the README.

**Comment by unclechu** [comment]
@sgf-dma Actually I’ve implemented drawing of the letters manually using simple lines. So now the issue with fonts disappears.
