### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by psikoz** [unclechu/place-cursor-at#2]
Hey @unclechu , I designed a logo by combining keyboard and mouse icons for you. If there is anything else you want, you can tell me. WDYT? 

![place](https://user-images.githubusercontent.com/40601249/42883906-922d9950-8aa5-11e8-95cc-3d27b2e67672.jpg)

**Comment by unclechu** [comment]
@psikoz Looks good to me. Do you have it as SVG? Which license you're about to use for this logo?

**Comment by psikoz** [comment]
Yes, I will send you a pr for all variations. Which font color do you like? Black or blue?

Also, Also, Which icon style do you like?  Please tell me the variations you like. 

![plc](https://user-images.githubusercontent.com/40601249/42933892-95335730-8b4e-11e8-97bd-cd215ce33c54.jpg)

**Comment by unclechu** [comment]
@psikoz Let's take first one, since any other edge is rounded but this invisible split line cuts it sharp. First one feels more consistent.

**Comment by psikoz** [comment]
you are actually right. So i sent a pull request. Can you check it?

**Comment by psikoz** [comment]
This logo is licensed under a Creative Commons Attribution 4.0 International License. (https://creativecommons.org/licenses/by/4.0/)

**Comment by unclechu** [comment]
@psikoz Okay, now your change is finally merged. Thank you for your contribution! Sorry for the almost 3 years delay 😅. I’m not sure if your GitHub account is still alive but I don’t have your name to refer to, only your “psikoz” nickname. I added your nickname to the contributors list but maybe you would like to be referred by your real name or some special pseudonym? I’m closing the issue as *solved* but you are free to leave the requested feedback here.
